name: Build and deploy PHP app to Azure Web App - dpmu-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer Dependencies
        run: |
          cd Backend
          composer install --no-dev --optimize-autoloader

      - name: Copy .env
        run: |
          cd Backend
          cp .env.example .env
          php artisan key:generate

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: ./Backend

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'dpmu-backend'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
